swagger: '2.0'
info:
  description: API
  version: 1.0.0
  title: 桃園交通串接API
  # put the contact info for your development or API team

# all paths will be relative to the basePath specified
# basePath: /v1

# tags are used for organizing operations
tags:
- name: Bus
  description: 公車資訊
- name: developers
  description: Operations available to regular developers
# schemes:
# - http
paths:
  /api/v1/Bus/BusRoute/JsonAllRoute:
    get:
      tags:
      - Bus
      summary: searches inventory
      operationId: searchInventory
      description: |
        取得所有公車路線
      produces:
      - application/json
      #parameters:
      #- in: query
      #  name: searchString
      #  description: pass an optional search string for #looking up inventory
      #  required: false
      #  type: string
      #- in: query
      #  name: skip
      #  description: number of records to skip for pagination
      #  type: integer
      #  format: int32
      #  minimum: 0
      #- in: query
      #  name: limit
      #  description: maximum number of records to return
      #  type: integer
      #  format: int32
      #  minimum: 0
      #  maximum: 50
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/GetRoute'
        400:
          description: bad input parameter

definitions:
  GetRoute:
    type: object
    required:
    - RouteUID
    - RouteID
    - RouteName
    - GoDirection
    - BackDirection
    - DepartureStopNameZh
    - DestinationStopNameZh
    - GoHeadsign
    - BackHeadsign
    properties:
      RouteUID:
        type: string
      RouteID:
        type: string
      RouteName:
        type: string
      GoDirection:
        type: integer
      BackDirection:
        type: integer
      DepartureStopNameZh:
        type: string
      DestinationStopNameZh:
        type: string
      GoHeadsign:
        type: string
      BackHeadsign:
        type: string
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /huijoson/Taoyuan_Traffic/1.0.0
# Added by API Auto Mocking Plugin
schemes:
 - https
 - http