<?xml version="1.0" encoding="utf-8"?><Database Name="Taoyuan_Traffic" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLSERVER;Initial Catalog=Taoyuan_Traffic;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Taoyuan_TrafficConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BusDynamic" Member="BusDynamic">
    <Type Name="BusDynamic">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlateNumb" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OperatorID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RouteUID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RouteID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SubRouteUID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SubRouteID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Direction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Speed" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Azimuth" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DutyStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BusStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MessageType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GPSTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SrcRecTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SrcUpdateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PositionLat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PositionLon" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SubRouteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RouteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BusRoute" Member="BusRoute">
    <Type Name="BusRoute">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RouteUID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="RouteID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="OperatorIDs" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="AuthorityID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ProviderID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GoSubRouteUID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GoSubRouteID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GoOperatorIDs" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GoSubRouteName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GoHeadsign" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GoDirection" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BackSubRouteUID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BackSubRouteID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BackOperatorIDs" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BackSubRouteName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BackHeadsign" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BackDirection" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BusRouteType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RouteName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DepartureStopNameZh" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DestinationStopNameZh" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TraLine" Member="TraLine">
    <Type Name="TraLine">
      <Column Name="[LineNo]" Member="LineNo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LineID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LineNameZh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LineNameEn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LineSectionNameZh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LineSectionNameEn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsBranch" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TraStation" Member="TraStation">
    <Type Name="TraStation">
      <Column Name="StationID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Zh_tw" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="En" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PositionLat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PositionLon" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="StationAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StationPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OperatorID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StationClass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReservationCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TraClass" Member="TraClass">
    <Type Name="TraClass">
      <Column Name="TrainClassificationID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Zh_tw" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="En" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParkingInfo" Member="ParkingInfo">
    <Type Name="ParkingInfo">
      <Column Name="parkName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="areaId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="wgsX" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="totalSpace" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="introduction" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="wgsY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="parkId" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="payGuide" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="[_id]" Member="_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="surplusSpace" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="areaName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WeatherTable" Member="WeatherTable">
    <Type Name="WeatherTable">
      <Column Name="wID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="locationName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="geocode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="elementName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="startTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="endTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="elementValue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="parameterName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="parameterValue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dataTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="elementMeasure" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AlertTable" Member="AlertTable">
    <Type Name="AlertTable">
      <Column Name="alertID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="updated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="term" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RealTimeTable" Member="RealTimeTable">
    <Type Name="RealTimeTable">
      <Column Name="region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="srcdetail" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="areaNm" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="direction" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="y1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="happentime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="roadtype" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="road" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="modDttm" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(600)" CanBeNull="true" />
      <Column Name="happendate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="x1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UBikeTable" Member="UBikeTable">
    <Type Name="UBikeTable">
      <Column Name="[_id]" Member="_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sna" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tot" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sbi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sarea" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mday" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lng" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ar" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="sareaen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="snaen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="aren" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="bemp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="act" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>