#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taoyuan_Traffic.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Taoyuan_Traffic")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertBusDynamic(BusDynamic instance);
    partial void UpdateBusDynamic(BusDynamic instance);
    partial void DeleteBusDynamic(BusDynamic instance);
    partial void InsertBusRoute(BusRoute instance);
    partial void UpdateBusRoute(BusRoute instance);
    partial void DeleteBusRoute(BusRoute instance);
    partial void InsertTraLine(TraLine instance);
    partial void UpdateTraLine(TraLine instance);
    partial void DeleteTraLine(TraLine instance);
    partial void InsertTraStation(TraStation instance);
    partial void UpdateTraStation(TraStation instance);
    partial void DeleteTraStation(TraStation instance);
    partial void InsertTraClass(TraClass instance);
    partial void UpdateTraClass(TraClass instance);
    partial void DeleteTraClass(TraClass instance);
    partial void InsertParkingInfo(ParkingInfo instance);
    partial void UpdateParkingInfo(ParkingInfo instance);
    partial void DeleteParkingInfo(ParkingInfo instance);
    partial void InsertWeatherTable(WeatherTable instance);
    partial void UpdateWeatherTable(WeatherTable instance);
    partial void DeleteWeatherTable(WeatherTable instance);
    partial void InsertAlertTable(AlertTable instance);
    partial void UpdateAlertTable(AlertTable instance);
    partial void DeleteAlertTable(AlertTable instance);
    partial void InsertRealTimeTable(RealTimeTable instance);
    partial void UpdateRealTimeTable(RealTimeTable instance);
    partial void DeleteRealTimeTable(RealTimeTable instance);
    partial void InsertUBikeTable(UBikeTable instance);
    partial void UpdateUBikeTable(UBikeTable instance);
    partial void DeleteUBikeTable(UBikeTable instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Taoyuan_TrafficConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BusDynamic> BusDynamic
		{
			get
			{
				return this.GetTable<BusDynamic>();
			}
		}
		
		public System.Data.Linq.Table<BusRoute> BusRoute
		{
			get
			{
				return this.GetTable<BusRoute>();
			}
		}
		
		public System.Data.Linq.Table<TraLine> TraLine
		{
			get
			{
				return this.GetTable<TraLine>();
			}
		}
		
		public System.Data.Linq.Table<TraStation> TraStation
		{
			get
			{
				return this.GetTable<TraStation>();
			}
		}
		
		public System.Data.Linq.Table<TraClass> TraClass
		{
			get
			{
				return this.GetTable<TraClass>();
			}
		}
		
		public System.Data.Linq.Table<ParkingInfo> ParkingInfo
		{
			get
			{
				return this.GetTable<ParkingInfo>();
			}
		}
		
		public System.Data.Linq.Table<WeatherTable> WeatherTable
		{
			get
			{
				return this.GetTable<WeatherTable>();
			}
		}
		
		public System.Data.Linq.Table<AlertTable> AlertTable
		{
			get
			{
				return this.GetTable<AlertTable>();
			}
		}
		
		public System.Data.Linq.Table<RealTimeTable> RealTimeTable
		{
			get
			{
				return this.GetTable<RealTimeTable>();
			}
		}
		
		public System.Data.Linq.Table<UBikeTable> UBikeTable
		{
			get
			{
				return this.GetTable<UBikeTable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BusDynamic")]
	public partial class BusDynamic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PlateNumb;
		
		private string _OperatorID;
		
		private string _RouteUID;
		
		private string _RouteID;
		
		private string _SubRouteUID;
		
		private string _SubRouteID;
		
		private System.Nullable<int> _Direction;
		
		private System.Nullable<double> _Speed;
		
		private System.Nullable<double> _Azimuth;
		
		private System.Nullable<int> _DutyStatus;
		
		private System.Nullable<int> _BusStatus;
		
		private System.Nullable<int> _MessageType;
		
		private System.Nullable<System.DateTime> _GPSTime;
		
		private System.Nullable<System.DateTime> _SrcRecTime;
		
		private System.Nullable<System.DateTime> _SrcUpdateTime;
		
		private System.Nullable<System.DateTime> _UpdateTime;
		
		private System.Nullable<double> _PositionLat;
		
		private System.Nullable<double> _PositionLon;
		
		private string _SubRouteName;
		
		private string _RouteName;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPlateNumbChanging(string value);
    partial void OnPlateNumbChanged();
    partial void OnOperatorIDChanging(string value);
    partial void OnOperatorIDChanged();
    partial void OnRouteUIDChanging(string value);
    partial void OnRouteUIDChanged();
    partial void OnRouteIDChanging(string value);
    partial void OnRouteIDChanged();
    partial void OnSubRouteUIDChanging(string value);
    partial void OnSubRouteUIDChanged();
    partial void OnSubRouteIDChanging(string value);
    partial void OnSubRouteIDChanged();
    partial void OnDirectionChanging(System.Nullable<int> value);
    partial void OnDirectionChanged();
    partial void OnSpeedChanging(System.Nullable<double> value);
    partial void OnSpeedChanged();
    partial void OnAzimuthChanging(System.Nullable<double> value);
    partial void OnAzimuthChanged();
    partial void OnDutyStatusChanging(System.Nullable<int> value);
    partial void OnDutyStatusChanged();
    partial void OnBusStatusChanging(System.Nullable<int> value);
    partial void OnBusStatusChanged();
    partial void OnMessageTypeChanging(System.Nullable<int> value);
    partial void OnMessageTypeChanged();
    partial void OnGPSTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnGPSTimeChanged();
    partial void OnSrcRecTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnSrcRecTimeChanged();
    partial void OnSrcUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnSrcUpdateTimeChanged();
    partial void OnUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateTimeChanged();
    partial void OnPositionLatChanging(System.Nullable<double> value);
    partial void OnPositionLatChanged();
    partial void OnPositionLonChanging(System.Nullable<double> value);
    partial void OnPositionLonChanged();
    partial void OnSubRouteNameChanging(string value);
    partial void OnSubRouteNameChanged();
    partial void OnRouteNameChanging(string value);
    partial void OnRouteNameChanged();
    #endregion
		
		public BusDynamic()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlateNumb", DbType="VarChar(20)")]
		public string PlateNumb
		{
			get
			{
				return this._PlateNumb;
			}
			set
			{
				if ((this._PlateNumb != value))
				{
					this.OnPlateNumbChanging(value);
					this.SendPropertyChanging();
					this._PlateNumb = value;
					this.SendPropertyChanged("PlateNumb");
					this.OnPlateNumbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorID", DbType="VarChar(20)")]
		public string OperatorID
		{
			get
			{
				return this._OperatorID;
			}
			set
			{
				if ((this._OperatorID != value))
				{
					this.OnOperatorIDChanging(value);
					this.SendPropertyChanging();
					this._OperatorID = value;
					this.SendPropertyChanged("OperatorID");
					this.OnOperatorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteUID", DbType="VarChar(20)")]
		public string RouteUID
		{
			get
			{
				return this._RouteUID;
			}
			set
			{
				if ((this._RouteUID != value))
				{
					this.OnRouteUIDChanging(value);
					this.SendPropertyChanging();
					this._RouteUID = value;
					this.SendPropertyChanged("RouteUID");
					this.OnRouteUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteID", DbType="VarChar(20)")]
		public string RouteID
		{
			get
			{
				return this._RouteID;
			}
			set
			{
				if ((this._RouteID != value))
				{
					this.OnRouteIDChanging(value);
					this.SendPropertyChanging();
					this._RouteID = value;
					this.SendPropertyChanged("RouteID");
					this.OnRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubRouteUID", DbType="VarChar(20)")]
		public string SubRouteUID
		{
			get
			{
				return this._SubRouteUID;
			}
			set
			{
				if ((this._SubRouteUID != value))
				{
					this.OnSubRouteUIDChanging(value);
					this.SendPropertyChanging();
					this._SubRouteUID = value;
					this.SendPropertyChanged("SubRouteUID");
					this.OnSubRouteUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubRouteID", DbType="VarChar(20)")]
		public string SubRouteID
		{
			get
			{
				return this._SubRouteID;
			}
			set
			{
				if ((this._SubRouteID != value))
				{
					this.OnSubRouteIDChanging(value);
					this.SendPropertyChanging();
					this._SubRouteID = value;
					this.SendPropertyChanged("SubRouteID");
					this.OnSubRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direction", DbType="Int")]
		public System.Nullable<int> Direction
		{
			get
			{
				return this._Direction;
			}
			set
			{
				if ((this._Direction != value))
				{
					this.OnDirectionChanging(value);
					this.SendPropertyChanging();
					this._Direction = value;
					this.SendPropertyChanged("Direction");
					this.OnDirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Speed", DbType="Float")]
		public System.Nullable<double> Speed
		{
			get
			{
				return this._Speed;
			}
			set
			{
				if ((this._Speed != value))
				{
					this.OnSpeedChanging(value);
					this.SendPropertyChanging();
					this._Speed = value;
					this.SendPropertyChanged("Speed");
					this.OnSpeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Azimuth", DbType="Float")]
		public System.Nullable<double> Azimuth
		{
			get
			{
				return this._Azimuth;
			}
			set
			{
				if ((this._Azimuth != value))
				{
					this.OnAzimuthChanging(value);
					this.SendPropertyChanging();
					this._Azimuth = value;
					this.SendPropertyChanged("Azimuth");
					this.OnAzimuthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DutyStatus", DbType="Int")]
		public System.Nullable<int> DutyStatus
		{
			get
			{
				return this._DutyStatus;
			}
			set
			{
				if ((this._DutyStatus != value))
				{
					this.OnDutyStatusChanging(value);
					this.SendPropertyChanging();
					this._DutyStatus = value;
					this.SendPropertyChanged("DutyStatus");
					this.OnDutyStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusStatus", DbType="Int")]
		public System.Nullable<int> BusStatus
		{
			get
			{
				return this._BusStatus;
			}
			set
			{
				if ((this._BusStatus != value))
				{
					this.OnBusStatusChanging(value);
					this.SendPropertyChanging();
					this._BusStatus = value;
					this.SendPropertyChanged("BusStatus");
					this.OnBusStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageType", DbType="Int")]
		public System.Nullable<int> MessageType
		{
			get
			{
				return this._MessageType;
			}
			set
			{
				if ((this._MessageType != value))
				{
					this.OnMessageTypeChanging(value);
					this.SendPropertyChanging();
					this._MessageType = value;
					this.SendPropertyChanged("MessageType");
					this.OnMessageTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPSTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> GPSTime
		{
			get
			{
				return this._GPSTime;
			}
			set
			{
				if ((this._GPSTime != value))
				{
					this.OnGPSTimeChanging(value);
					this.SendPropertyChanging();
					this._GPSTime = value;
					this.SendPropertyChanged("GPSTime");
					this.OnGPSTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrcRecTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> SrcRecTime
		{
			get
			{
				return this._SrcRecTime;
			}
			set
			{
				if ((this._SrcRecTime != value))
				{
					this.OnSrcRecTimeChanging(value);
					this.SendPropertyChanging();
					this._SrcRecTime = value;
					this.SendPropertyChanged("SrcRecTime");
					this.OnSrcRecTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrcUpdateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> SrcUpdateTime
		{
			get
			{
				return this._SrcUpdateTime;
			}
			set
			{
				if ((this._SrcUpdateTime != value))
				{
					this.OnSrcUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._SrcUpdateTime = value;
					this.SendPropertyChanged("SrcUpdateTime");
					this.OnSrcUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionLat", DbType="Float")]
		public System.Nullable<double> PositionLat
		{
			get
			{
				return this._PositionLat;
			}
			set
			{
				if ((this._PositionLat != value))
				{
					this.OnPositionLatChanging(value);
					this.SendPropertyChanging();
					this._PositionLat = value;
					this.SendPropertyChanged("PositionLat");
					this.OnPositionLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionLon", DbType="Float")]
		public System.Nullable<double> PositionLon
		{
			get
			{
				return this._PositionLon;
			}
			set
			{
				if ((this._PositionLon != value))
				{
					this.OnPositionLonChanging(value);
					this.SendPropertyChanging();
					this._PositionLon = value;
					this.SendPropertyChanged("PositionLon");
					this.OnPositionLonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubRouteName", DbType="VarChar(50)")]
		public string SubRouteName
		{
			get
			{
				return this._SubRouteName;
			}
			set
			{
				if ((this._SubRouteName != value))
				{
					this.OnSubRouteNameChanging(value);
					this.SendPropertyChanging();
					this._SubRouteName = value;
					this.SendPropertyChanged("SubRouteName");
					this.OnSubRouteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteName", DbType="VarChar(50)")]
		public string RouteName
		{
			get
			{
				return this._RouteName;
			}
			set
			{
				if ((this._RouteName != value))
				{
					this.OnRouteNameChanging(value);
					this.SendPropertyChanging();
					this._RouteName = value;
					this.SendPropertyChanged("RouteName");
					this.OnRouteNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BusRoute")]
	public partial class BusRoute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _RouteUID;
		
		private string _RouteID;
		
		private string _OperatorIDs;
		
		private string _AuthorityID;
		
		private string _ProviderID;
		
		private string _GoSubRouteUID;
		
		private string _GoSubRouteID;
		
		private string _GoOperatorIDs;
		
		private string _GoSubRouteName;
		
		private string _GoHeadsign;
		
		private System.Nullable<int> _GoDirection;
		
		private string _BackSubRouteUID;
		
		private string _BackSubRouteID;
		
		private string _BackOperatorIDs;
		
		private string _BackSubRouteName;
		
		private string _BackHeadsign;
		
		private System.Nullable<int> _BackDirection;
		
		private System.Nullable<int> _BusRouteType;
		
		private string _RouteName;
		
		private string _DepartureStopNameZh;
		
		private string _DestinationStopNameZh;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private System.Nullable<System.DateTime> _UpdateTime;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRouteUIDChanging(string value);
    partial void OnRouteUIDChanged();
    partial void OnRouteIDChanging(string value);
    partial void OnRouteIDChanged();
    partial void OnOperatorIDsChanging(string value);
    partial void OnOperatorIDsChanged();
    partial void OnAuthorityIDChanging(string value);
    partial void OnAuthorityIDChanged();
    partial void OnProviderIDChanging(string value);
    partial void OnProviderIDChanged();
    partial void OnGoSubRouteUIDChanging(string value);
    partial void OnGoSubRouteUIDChanged();
    partial void OnGoSubRouteIDChanging(string value);
    partial void OnGoSubRouteIDChanged();
    partial void OnGoOperatorIDsChanging(string value);
    partial void OnGoOperatorIDsChanged();
    partial void OnGoSubRouteNameChanging(string value);
    partial void OnGoSubRouteNameChanged();
    partial void OnGoHeadsignChanging(string value);
    partial void OnGoHeadsignChanged();
    partial void OnGoDirectionChanging(System.Nullable<int> value);
    partial void OnGoDirectionChanged();
    partial void OnBackSubRouteUIDChanging(string value);
    partial void OnBackSubRouteUIDChanged();
    partial void OnBackSubRouteIDChanging(string value);
    partial void OnBackSubRouteIDChanged();
    partial void OnBackOperatorIDsChanging(string value);
    partial void OnBackOperatorIDsChanged();
    partial void OnBackSubRouteNameChanging(string value);
    partial void OnBackSubRouteNameChanged();
    partial void OnBackHeadsignChanging(string value);
    partial void OnBackHeadsignChanged();
    partial void OnBackDirectionChanging(System.Nullable<int> value);
    partial void OnBackDirectionChanged();
    partial void OnBusRouteTypeChanging(System.Nullable<int> value);
    partial void OnBusRouteTypeChanged();
    partial void OnRouteNameChanging(string value);
    partial void OnRouteNameChanged();
    partial void OnDepartureStopNameZhChanging(string value);
    partial void OnDepartureStopNameZhChanged();
    partial void OnDestinationStopNameZhChanging(string value);
    partial void OnDestinationStopNameZhChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateTimeChanged();
    #endregion
		
		public BusRoute()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteUID", DbType="NVarChar(30)")]
		public string RouteUID
		{
			get
			{
				return this._RouteUID;
			}
			set
			{
				if ((this._RouteUID != value))
				{
					this.OnRouteUIDChanging(value);
					this.SendPropertyChanging();
					this._RouteUID = value;
					this.SendPropertyChanged("RouteUID");
					this.OnRouteUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteID", DbType="NVarChar(30)")]
		public string RouteID
		{
			get
			{
				return this._RouteID;
			}
			set
			{
				if ((this._RouteID != value))
				{
					this.OnRouteIDChanging(value);
					this.SendPropertyChanging();
					this._RouteID = value;
					this.SendPropertyChanged("RouteID");
					this.OnRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorIDs", DbType="NVarChar(30)")]
		public string OperatorIDs
		{
			get
			{
				return this._OperatorIDs;
			}
			set
			{
				if ((this._OperatorIDs != value))
				{
					this.OnOperatorIDsChanging(value);
					this.SendPropertyChanging();
					this._OperatorIDs = value;
					this.SendPropertyChanged("OperatorIDs");
					this.OnOperatorIDsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorityID", DbType="NVarChar(30)")]
		public string AuthorityID
		{
			get
			{
				return this._AuthorityID;
			}
			set
			{
				if ((this._AuthorityID != value))
				{
					this.OnAuthorityIDChanging(value);
					this.SendPropertyChanging();
					this._AuthorityID = value;
					this.SendPropertyChanged("AuthorityID");
					this.OnAuthorityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderID", DbType="NVarChar(30)")]
		public string ProviderID
		{
			get
			{
				return this._ProviderID;
			}
			set
			{
				if ((this._ProviderID != value))
				{
					this.OnProviderIDChanging(value);
					this.SendPropertyChanging();
					this._ProviderID = value;
					this.SendPropertyChanged("ProviderID");
					this.OnProviderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoSubRouteUID", DbType="NVarChar(30)")]
		public string GoSubRouteUID
		{
			get
			{
				return this._GoSubRouteUID;
			}
			set
			{
				if ((this._GoSubRouteUID != value))
				{
					this.OnGoSubRouteUIDChanging(value);
					this.SendPropertyChanging();
					this._GoSubRouteUID = value;
					this.SendPropertyChanged("GoSubRouteUID");
					this.OnGoSubRouteUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoSubRouteID", DbType="NVarChar(30)")]
		public string GoSubRouteID
		{
			get
			{
				return this._GoSubRouteID;
			}
			set
			{
				if ((this._GoSubRouteID != value))
				{
					this.OnGoSubRouteIDChanging(value);
					this.SendPropertyChanging();
					this._GoSubRouteID = value;
					this.SendPropertyChanged("GoSubRouteID");
					this.OnGoSubRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoOperatorIDs", DbType="NVarChar(30)")]
		public string GoOperatorIDs
		{
			get
			{
				return this._GoOperatorIDs;
			}
			set
			{
				if ((this._GoOperatorIDs != value))
				{
					this.OnGoOperatorIDsChanging(value);
					this.SendPropertyChanging();
					this._GoOperatorIDs = value;
					this.SendPropertyChanged("GoOperatorIDs");
					this.OnGoOperatorIDsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoSubRouteName", DbType="NVarChar(30)")]
		public string GoSubRouteName
		{
			get
			{
				return this._GoSubRouteName;
			}
			set
			{
				if ((this._GoSubRouteName != value))
				{
					this.OnGoSubRouteNameChanging(value);
					this.SendPropertyChanging();
					this._GoSubRouteName = value;
					this.SendPropertyChanged("GoSubRouteName");
					this.OnGoSubRouteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoHeadsign", DbType="NVarChar(30)")]
		public string GoHeadsign
		{
			get
			{
				return this._GoHeadsign;
			}
			set
			{
				if ((this._GoHeadsign != value))
				{
					this.OnGoHeadsignChanging(value);
					this.SendPropertyChanging();
					this._GoHeadsign = value;
					this.SendPropertyChanged("GoHeadsign");
					this.OnGoHeadsignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoDirection", DbType="Int")]
		public System.Nullable<int> GoDirection
		{
			get
			{
				return this._GoDirection;
			}
			set
			{
				if ((this._GoDirection != value))
				{
					this.OnGoDirectionChanging(value);
					this.SendPropertyChanging();
					this._GoDirection = value;
					this.SendPropertyChanged("GoDirection");
					this.OnGoDirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackSubRouteUID", DbType="NVarChar(30)")]
		public string BackSubRouteUID
		{
			get
			{
				return this._BackSubRouteUID;
			}
			set
			{
				if ((this._BackSubRouteUID != value))
				{
					this.OnBackSubRouteUIDChanging(value);
					this.SendPropertyChanging();
					this._BackSubRouteUID = value;
					this.SendPropertyChanged("BackSubRouteUID");
					this.OnBackSubRouteUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackSubRouteID", DbType="NVarChar(30)")]
		public string BackSubRouteID
		{
			get
			{
				return this._BackSubRouteID;
			}
			set
			{
				if ((this._BackSubRouteID != value))
				{
					this.OnBackSubRouteIDChanging(value);
					this.SendPropertyChanging();
					this._BackSubRouteID = value;
					this.SendPropertyChanged("BackSubRouteID");
					this.OnBackSubRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackOperatorIDs", DbType="NVarChar(30)")]
		public string BackOperatorIDs
		{
			get
			{
				return this._BackOperatorIDs;
			}
			set
			{
				if ((this._BackOperatorIDs != value))
				{
					this.OnBackOperatorIDsChanging(value);
					this.SendPropertyChanging();
					this._BackOperatorIDs = value;
					this.SendPropertyChanged("BackOperatorIDs");
					this.OnBackOperatorIDsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackSubRouteName", DbType="NVarChar(30)")]
		public string BackSubRouteName
		{
			get
			{
				return this._BackSubRouteName;
			}
			set
			{
				if ((this._BackSubRouteName != value))
				{
					this.OnBackSubRouteNameChanging(value);
					this.SendPropertyChanging();
					this._BackSubRouteName = value;
					this.SendPropertyChanged("BackSubRouteName");
					this.OnBackSubRouteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackHeadsign", DbType="NVarChar(30)")]
		public string BackHeadsign
		{
			get
			{
				return this._BackHeadsign;
			}
			set
			{
				if ((this._BackHeadsign != value))
				{
					this.OnBackHeadsignChanging(value);
					this.SendPropertyChanging();
					this._BackHeadsign = value;
					this.SendPropertyChanged("BackHeadsign");
					this.OnBackHeadsignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackDirection", DbType="Int")]
		public System.Nullable<int> BackDirection
		{
			get
			{
				return this._BackDirection;
			}
			set
			{
				if ((this._BackDirection != value))
				{
					this.OnBackDirectionChanging(value);
					this.SendPropertyChanging();
					this._BackDirection = value;
					this.SendPropertyChanged("BackDirection");
					this.OnBackDirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusRouteType", DbType="Int")]
		public System.Nullable<int> BusRouteType
		{
			get
			{
				return this._BusRouteType;
			}
			set
			{
				if ((this._BusRouteType != value))
				{
					this.OnBusRouteTypeChanging(value);
					this.SendPropertyChanging();
					this._BusRouteType = value;
					this.SendPropertyChanged("BusRouteType");
					this.OnBusRouteTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteName", DbType="NVarChar(30)")]
		public string RouteName
		{
			get
			{
				return this._RouteName;
			}
			set
			{
				if ((this._RouteName != value))
				{
					this.OnRouteNameChanging(value);
					this.SendPropertyChanging();
					this._RouteName = value;
					this.SendPropertyChanged("RouteName");
					this.OnRouteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartureStopNameZh", DbType="NVarChar(30)")]
		public string DepartureStopNameZh
		{
			get
			{
				return this._DepartureStopNameZh;
			}
			set
			{
				if ((this._DepartureStopNameZh != value))
				{
					this.OnDepartureStopNameZhChanging(value);
					this.SendPropertyChanging();
					this._DepartureStopNameZh = value;
					this.SendPropertyChanged("DepartureStopNameZh");
					this.OnDepartureStopNameZhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationStopNameZh", DbType="NVarChar(30)")]
		public string DestinationStopNameZh
		{
			get
			{
				return this._DestinationStopNameZh;
			}
			set
			{
				if ((this._DestinationStopNameZh != value))
				{
					this.OnDestinationStopNameZhChanging(value);
					this.SendPropertyChanging();
					this._DestinationStopNameZh = value;
					this.SendPropertyChanged("DestinationStopNameZh");
					this.OnDestinationStopNameZhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TraLine")]
	public partial class TraLine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LineNo;
		
		private string _LineID;
		
		private string _LineNameZh;
		
		private string _LineNameEn;
		
		private string _LineSectionNameZh;
		
		private string _LineSectionNameEn;
		
		private System.Nullable<bool> _IsBranch;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLineNoChanging(string value);
    partial void OnLineNoChanged();
    partial void OnLineIDChanging(string value);
    partial void OnLineIDChanged();
    partial void OnLineNameZhChanging(string value);
    partial void OnLineNameZhChanged();
    partial void OnLineNameEnChanging(string value);
    partial void OnLineNameEnChanged();
    partial void OnLineSectionNameZhChanging(string value);
    partial void OnLineSectionNameZhChanged();
    partial void OnLineSectionNameEnChanging(string value);
    partial void OnLineSectionNameEnChanged();
    partial void OnIsBranchChanging(System.Nullable<bool> value);
    partial void OnIsBranchChanged();
    #endregion
		
		public TraLine()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[LineNo]", Storage="_LineNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LineNo
		{
			get
			{
				return this._LineNo;
			}
			set
			{
				if ((this._LineNo != value))
				{
					this.OnLineNoChanging(value);
					this.SendPropertyChanging();
					this._LineNo = value;
					this.SendPropertyChanged("LineNo");
					this.OnLineNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineID", DbType="NVarChar(50)")]
		public string LineID
		{
			get
			{
				return this._LineID;
			}
			set
			{
				if ((this._LineID != value))
				{
					this.OnLineIDChanging(value);
					this.SendPropertyChanging();
					this._LineID = value;
					this.SendPropertyChanged("LineID");
					this.OnLineIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineNameZh", DbType="NVarChar(50)")]
		public string LineNameZh
		{
			get
			{
				return this._LineNameZh;
			}
			set
			{
				if ((this._LineNameZh != value))
				{
					this.OnLineNameZhChanging(value);
					this.SendPropertyChanging();
					this._LineNameZh = value;
					this.SendPropertyChanged("LineNameZh");
					this.OnLineNameZhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineNameEn", DbType="NVarChar(50)")]
		public string LineNameEn
		{
			get
			{
				return this._LineNameEn;
			}
			set
			{
				if ((this._LineNameEn != value))
				{
					this.OnLineNameEnChanging(value);
					this.SendPropertyChanging();
					this._LineNameEn = value;
					this.SendPropertyChanged("LineNameEn");
					this.OnLineNameEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineSectionNameZh", DbType="NVarChar(50)")]
		public string LineSectionNameZh
		{
			get
			{
				return this._LineSectionNameZh;
			}
			set
			{
				if ((this._LineSectionNameZh != value))
				{
					this.OnLineSectionNameZhChanging(value);
					this.SendPropertyChanging();
					this._LineSectionNameZh = value;
					this.SendPropertyChanged("LineSectionNameZh");
					this.OnLineSectionNameZhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineSectionNameEn", DbType="NVarChar(50)")]
		public string LineSectionNameEn
		{
			get
			{
				return this._LineSectionNameEn;
			}
			set
			{
				if ((this._LineSectionNameEn != value))
				{
					this.OnLineSectionNameEnChanging(value);
					this.SendPropertyChanging();
					this._LineSectionNameEn = value;
					this.SendPropertyChanged("LineSectionNameEn");
					this.OnLineSectionNameEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBranch", DbType="Bit")]
		public System.Nullable<bool> IsBranch
		{
			get
			{
				return this._IsBranch;
			}
			set
			{
				if ((this._IsBranch != value))
				{
					this.OnIsBranchChanging(value);
					this.SendPropertyChanging();
					this._IsBranch = value;
					this.SendPropertyChanged("IsBranch");
					this.OnIsBranchChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TraStation")]
	public partial class TraStation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _StationID;
		
		private string _Zh_tw;
		
		private string _En;
		
		private System.Nullable<double> _PositionLat;
		
		private System.Nullable<double> _PositionLon;
		
		private string _StationAddress;
		
		private string _StationPhone;
		
		private string _OperatorID;
		
		private string _StationClass;
		
		private string _ReservationCode;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStationIDChanging(string value);
    partial void OnStationIDChanged();
    partial void OnZh_twChanging(string value);
    partial void OnZh_twChanged();
    partial void OnEnChanging(string value);
    partial void OnEnChanged();
    partial void OnPositionLatChanging(System.Nullable<double> value);
    partial void OnPositionLatChanged();
    partial void OnPositionLonChanging(System.Nullable<double> value);
    partial void OnPositionLonChanged();
    partial void OnStationAddressChanging(string value);
    partial void OnStationAddressChanged();
    partial void OnStationPhoneChanging(string value);
    partial void OnStationPhoneChanged();
    partial void OnOperatorIDChanging(string value);
    partial void OnOperatorIDChanged();
    partial void OnStationClassChanging(string value);
    partial void OnStationClassChanged();
    partial void OnReservationCodeChanging(string value);
    partial void OnReservationCodeChanged();
    #endregion
		
		public TraStation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StationID
		{
			get
			{
				return this._StationID;
			}
			set
			{
				if ((this._StationID != value))
				{
					this.OnStationIDChanging(value);
					this.SendPropertyChanging();
					this._StationID = value;
					this.SendPropertyChanged("StationID");
					this.OnStationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zh_tw", DbType="NVarChar(50)")]
		public string Zh_tw
		{
			get
			{
				return this._Zh_tw;
			}
			set
			{
				if ((this._Zh_tw != value))
				{
					this.OnZh_twChanging(value);
					this.SendPropertyChanging();
					this._Zh_tw = value;
					this.SendPropertyChanged("Zh_tw");
					this.OnZh_twChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_En", DbType="NVarChar(50)")]
		public string En
		{
			get
			{
				return this._En;
			}
			set
			{
				if ((this._En != value))
				{
					this.OnEnChanging(value);
					this.SendPropertyChanging();
					this._En = value;
					this.SendPropertyChanged("En");
					this.OnEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionLat", DbType="Float")]
		public System.Nullable<double> PositionLat
		{
			get
			{
				return this._PositionLat;
			}
			set
			{
				if ((this._PositionLat != value))
				{
					this.OnPositionLatChanging(value);
					this.SendPropertyChanging();
					this._PositionLat = value;
					this.SendPropertyChanged("PositionLat");
					this.OnPositionLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionLon", DbType="Float")]
		public System.Nullable<double> PositionLon
		{
			get
			{
				return this._PositionLon;
			}
			set
			{
				if ((this._PositionLon != value))
				{
					this.OnPositionLonChanging(value);
					this.SendPropertyChanging();
					this._PositionLon = value;
					this.SendPropertyChanged("PositionLon");
					this.OnPositionLonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationAddress", DbType="NVarChar(50)")]
		public string StationAddress
		{
			get
			{
				return this._StationAddress;
			}
			set
			{
				if ((this._StationAddress != value))
				{
					this.OnStationAddressChanging(value);
					this.SendPropertyChanging();
					this._StationAddress = value;
					this.SendPropertyChanged("StationAddress");
					this.OnStationAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationPhone", DbType="NVarChar(50)")]
		public string StationPhone
		{
			get
			{
				return this._StationPhone;
			}
			set
			{
				if ((this._StationPhone != value))
				{
					this.OnStationPhoneChanging(value);
					this.SendPropertyChanging();
					this._StationPhone = value;
					this.SendPropertyChanged("StationPhone");
					this.OnStationPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorID", DbType="NVarChar(50)")]
		public string OperatorID
		{
			get
			{
				return this._OperatorID;
			}
			set
			{
				if ((this._OperatorID != value))
				{
					this.OnOperatorIDChanging(value);
					this.SendPropertyChanging();
					this._OperatorID = value;
					this.SendPropertyChanged("OperatorID");
					this.OnOperatorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationClass", DbType="NVarChar(50)")]
		public string StationClass
		{
			get
			{
				return this._StationClass;
			}
			set
			{
				if ((this._StationClass != value))
				{
					this.OnStationClassChanging(value);
					this.SendPropertyChanging();
					this._StationClass = value;
					this.SendPropertyChanged("StationClass");
					this.OnStationClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationCode", DbType="NVarChar(50)")]
		public string ReservationCode
		{
			get
			{
				return this._ReservationCode;
			}
			set
			{
				if ((this._ReservationCode != value))
				{
					this.OnReservationCodeChanging(value);
					this.SendPropertyChanging();
					this._ReservationCode = value;
					this.SendPropertyChanged("ReservationCode");
					this.OnReservationCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TraClass")]
	public partial class TraClass : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TrainClassificationID;
		
		private string _Zh_tw;
		
		private string _En;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTrainClassificationIDChanging(string value);
    partial void OnTrainClassificationIDChanged();
    partial void OnZh_twChanging(string value);
    partial void OnZh_twChanged();
    partial void OnEnChanging(string value);
    partial void OnEnChanged();
    #endregion
		
		public TraClass()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrainClassificationID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TrainClassificationID
		{
			get
			{
				return this._TrainClassificationID;
			}
			set
			{
				if ((this._TrainClassificationID != value))
				{
					this.OnTrainClassificationIDChanging(value);
					this.SendPropertyChanging();
					this._TrainClassificationID = value;
					this.SendPropertyChanged("TrainClassificationID");
					this.OnTrainClassificationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zh_tw", DbType="NVarChar(50)")]
		public string Zh_tw
		{
			get
			{
				return this._Zh_tw;
			}
			set
			{
				if ((this._Zh_tw != value))
				{
					this.OnZh_twChanging(value);
					this.SendPropertyChanging();
					this._Zh_tw = value;
					this.SendPropertyChanged("Zh_tw");
					this.OnZh_twChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_En", DbType="NChar(10)")]
		public string En
		{
			get
			{
				return this._En;
			}
			set
			{
				if ((this._En != value))
				{
					this.OnEnChanging(value);
					this.SendPropertyChanging();
					this._En = value;
					this.SendPropertyChanged("En");
					this.OnEnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ParkingInfo")]
	public partial class ParkingInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _parkName;
		
		private string _areaId;
		
		private System.Nullable<double> _wgsX;
		
		private System.Nullable<int> _totalSpace;
		
		private string _introduction;
		
		private System.Nullable<double> _wgsY;
		
		private string _parkId;
		
		private string _address;
		
		private string _payGuide;
		
		private System.Nullable<int> @__id;
		
		private string _surplusSpace;
		
		private string _areaName;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnparkNameChanging(string value);
    partial void OnparkNameChanged();
    partial void OnareaIdChanging(string value);
    partial void OnareaIdChanged();
    partial void OnwgsXChanging(System.Nullable<double> value);
    partial void OnwgsXChanged();
    partial void OntotalSpaceChanging(System.Nullable<int> value);
    partial void OntotalSpaceChanged();
    partial void OnintroductionChanging(string value);
    partial void OnintroductionChanged();
    partial void OnwgsYChanging(System.Nullable<double> value);
    partial void OnwgsYChanged();
    partial void OnparkIdChanging(string value);
    partial void OnparkIdChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnpayGuideChanging(string value);
    partial void OnpayGuideChanged();
    partial void On_idChanging(System.Nullable<int> value);
    partial void On_idChanged();
    partial void OnsurplusSpaceChanging(string value);
    partial void OnsurplusSpaceChanged();
    partial void OnareaNameChanging(string value);
    partial void OnareaNameChanged();
    #endregion
		
		public ParkingInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parkName", DbType="NVarChar(50)")]
		public string parkName
		{
			get
			{
				return this._parkName;
			}
			set
			{
				if ((this._parkName != value))
				{
					this.OnparkNameChanging(value);
					this.SendPropertyChanging();
					this._parkName = value;
					this.SendPropertyChanged("parkName");
					this.OnparkNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaId", DbType="NVarChar(50)")]
		public string areaId
		{
			get
			{
				return this._areaId;
			}
			set
			{
				if ((this._areaId != value))
				{
					this.OnareaIdChanging(value);
					this.SendPropertyChanging();
					this._areaId = value;
					this.SendPropertyChanged("areaId");
					this.OnareaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wgsX", DbType="Float")]
		public System.Nullable<double> wgsX
		{
			get
			{
				return this._wgsX;
			}
			set
			{
				if ((this._wgsX != value))
				{
					this.OnwgsXChanging(value);
					this.SendPropertyChanging();
					this._wgsX = value;
					this.SendPropertyChanged("wgsX");
					this.OnwgsXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalSpace", DbType="Int")]
		public System.Nullable<int> totalSpace
		{
			get
			{
				return this._totalSpace;
			}
			set
			{
				if ((this._totalSpace != value))
				{
					this.OntotalSpaceChanging(value);
					this.SendPropertyChanging();
					this._totalSpace = value;
					this.SendPropertyChanged("totalSpace");
					this.OntotalSpaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_introduction", DbType="NVarChar(50)")]
		public string introduction
		{
			get
			{
				return this._introduction;
			}
			set
			{
				if ((this._introduction != value))
				{
					this.OnintroductionChanging(value);
					this.SendPropertyChanging();
					this._introduction = value;
					this.SendPropertyChanged("introduction");
					this.OnintroductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wgsY", DbType="Float")]
		public System.Nullable<double> wgsY
		{
			get
			{
				return this._wgsY;
			}
			set
			{
				if ((this._wgsY != value))
				{
					this.OnwgsYChanging(value);
					this.SendPropertyChanging();
					this._wgsY = value;
					this.SendPropertyChanged("wgsY");
					this.OnwgsYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parkId", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string parkId
		{
			get
			{
				return this._parkId;
			}
			set
			{
				if ((this._parkId != value))
				{
					this.OnparkIdChanging(value);
					this.SendPropertyChanging();
					this._parkId = value;
					this.SendPropertyChanged("parkId");
					this.OnparkIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payGuide", DbType="NVarChar(200)")]
		public string payGuide
		{
			get
			{
				return this._payGuide;
			}
			set
			{
				if ((this._payGuide != value))
				{
					this.OnpayGuideChanging(value);
					this.SendPropertyChanging();
					this._payGuide = value;
					this.SendPropertyChanged("payGuide");
					this.OnpayGuideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", DbType="Int")]
		public System.Nullable<int> _id
		{
			get
			{
				return this.@__id;
			}
			set
			{
				if ((this.@__id != value))
				{
					this.On_idChanging(value);
					this.SendPropertyChanging();
					this.@__id = value;
					this.SendPropertyChanged("_id");
					this.On_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surplusSpace", DbType="NVarChar(50)")]
		public string surplusSpace
		{
			get
			{
				return this._surplusSpace;
			}
			set
			{
				if ((this._surplusSpace != value))
				{
					this.OnsurplusSpaceChanging(value);
					this.SendPropertyChanging();
					this._surplusSpace = value;
					this.SendPropertyChanged("surplusSpace");
					this.OnsurplusSpaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaName", DbType="NVarChar(50)")]
		public string areaName
		{
			get
			{
				return this._areaName;
			}
			set
			{
				if ((this._areaName != value))
				{
					this.OnareaNameChanging(value);
					this.SendPropertyChanging();
					this._areaName = value;
					this.SendPropertyChanged("areaName");
					this.OnareaNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WeatherTable")]
	public partial class WeatherTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _wID;
		
		private string _locationName;
		
		private string _geocode;
		
		private string _lat;
		
		private string _lon;
		
		private string _elementName;
		
		private string _startTime;
		
		private string _endTime;
		
		private string _elementValue;
		
		private string _parameterName;
		
		private string _parameterValue;
		
		private string _dataTime;
		
		private string _elementMeasure;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnwIDChanging(int value);
    partial void OnwIDChanged();
    partial void OnlocationNameChanging(string value);
    partial void OnlocationNameChanged();
    partial void OngeocodeChanging(string value);
    partial void OngeocodeChanged();
    partial void OnlatChanging(string value);
    partial void OnlatChanged();
    partial void OnlonChanging(string value);
    partial void OnlonChanged();
    partial void OnelementNameChanging(string value);
    partial void OnelementNameChanged();
    partial void OnstartTimeChanging(string value);
    partial void OnstartTimeChanged();
    partial void OnendTimeChanging(string value);
    partial void OnendTimeChanged();
    partial void OnelementValueChanging(string value);
    partial void OnelementValueChanged();
    partial void OnparameterNameChanging(string value);
    partial void OnparameterNameChanged();
    partial void OnparameterValueChanging(string value);
    partial void OnparameterValueChanged();
    partial void OndataTimeChanging(string value);
    partial void OndataTimeChanged();
    partial void OnelementMeasureChanging(string value);
    partial void OnelementMeasureChanged();
    #endregion
		
		public WeatherTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int wID
		{
			get
			{
				return this._wID;
			}
			set
			{
				if ((this._wID != value))
				{
					this.OnwIDChanging(value);
					this.SendPropertyChanging();
					this._wID = value;
					this.SendPropertyChanged("wID");
					this.OnwIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_locationName", DbType="NVarChar(50)")]
		public string locationName
		{
			get
			{
				return this._locationName;
			}
			set
			{
				if ((this._locationName != value))
				{
					this.OnlocationNameChanging(value);
					this.SendPropertyChanging();
					this._locationName = value;
					this.SendPropertyChanged("locationName");
					this.OnlocationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_geocode", DbType="NVarChar(50)")]
		public string geocode
		{
			get
			{
				return this._geocode;
			}
			set
			{
				if ((this._geocode != value))
				{
					this.OngeocodeChanging(value);
					this.SendPropertyChanging();
					this._geocode = value;
					this.SendPropertyChanged("geocode");
					this.OngeocodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="NVarChar(50)")]
		public string lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				if ((this._lat != value))
				{
					this.OnlatChanging(value);
					this.SendPropertyChanging();
					this._lat = value;
					this.SendPropertyChanged("lat");
					this.OnlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lon", DbType="NVarChar(50)")]
		public string lon
		{
			get
			{
				return this._lon;
			}
			set
			{
				if ((this._lon != value))
				{
					this.OnlonChanging(value);
					this.SendPropertyChanging();
					this._lon = value;
					this.SendPropertyChanged("lon");
					this.OnlonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_elementName", DbType="NVarChar(50)")]
		public string elementName
		{
			get
			{
				return this._elementName;
			}
			set
			{
				if ((this._elementName != value))
				{
					this.OnelementNameChanging(value);
					this.SendPropertyChanging();
					this._elementName = value;
					this.SendPropertyChanged("elementName");
					this.OnelementNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startTime", DbType="NVarChar(50)")]
		public string startTime
		{
			get
			{
				return this._startTime;
			}
			set
			{
				if ((this._startTime != value))
				{
					this.OnstartTimeChanging(value);
					this.SendPropertyChanging();
					this._startTime = value;
					this.SendPropertyChanged("startTime");
					this.OnstartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endTime", DbType="NVarChar(50)")]
		public string endTime
		{
			get
			{
				return this._endTime;
			}
			set
			{
				if ((this._endTime != value))
				{
					this.OnendTimeChanging(value);
					this.SendPropertyChanging();
					this._endTime = value;
					this.SendPropertyChanged("endTime");
					this.OnendTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_elementValue", DbType="NVarChar(50)")]
		public string elementValue
		{
			get
			{
				return this._elementValue;
			}
			set
			{
				if ((this._elementValue != value))
				{
					this.OnelementValueChanging(value);
					this.SendPropertyChanging();
					this._elementValue = value;
					this.SendPropertyChanged("elementValue");
					this.OnelementValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parameterName", DbType="NVarChar(50)")]
		public string parameterName
		{
			get
			{
				return this._parameterName;
			}
			set
			{
				if ((this._parameterName != value))
				{
					this.OnparameterNameChanging(value);
					this.SendPropertyChanging();
					this._parameterName = value;
					this.SendPropertyChanged("parameterName");
					this.OnparameterNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parameterValue", DbType="NVarChar(50)")]
		public string parameterValue
		{
			get
			{
				return this._parameterValue;
			}
			set
			{
				if ((this._parameterValue != value))
				{
					this.OnparameterValueChanging(value);
					this.SendPropertyChanging();
					this._parameterValue = value;
					this.SendPropertyChanged("parameterValue");
					this.OnparameterValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataTime", DbType="NVarChar(50)")]
		public string dataTime
		{
			get
			{
				return this._dataTime;
			}
			set
			{
				if ((this._dataTime != value))
				{
					this.OndataTimeChanging(value);
					this.SendPropertyChanging();
					this._dataTime = value;
					this.SendPropertyChanged("dataTime");
					this.OndataTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_elementMeasure", DbType="NVarChar(50)")]
		public string elementMeasure
		{
			get
			{
				return this._elementMeasure;
			}
			set
			{
				if ((this._elementMeasure != value))
				{
					this.OnelementMeasureChanging(value);
					this.SendPropertyChanging();
					this._elementMeasure = value;
					this.SendPropertyChanged("elementMeasure");
					this.OnelementMeasureChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlertTable")]
	public partial class AlertTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _alertID;
		
		private System.Nullable<System.DateTime> _updated;
		
		private string _name;
		
		private string _text;
		
		private string _term;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnalertIDChanging(int value);
    partial void OnalertIDChanged();
    partial void OnupdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void OntermChanging(string value);
    partial void OntermChanged();
    #endregion
		
		public AlertTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alertID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int alertID
		{
			get
			{
				return this._alertID;
			}
			set
			{
				if ((this._alertID != value))
				{
					this.OnalertIDChanging(value);
					this.SendPropertyChanging();
					this._alertID = value;
					this.SendPropertyChanged("alertID");
					this.OnalertIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated
		{
			get
			{
				return this._updated;
			}
			set
			{
				if ((this._updated != value))
				{
					this.OnupdatedChanging(value);
					this.SendPropertyChanging();
					this._updated = value;
					this.SendPropertyChanged("updated");
					this.OnupdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NVarChar(500)")]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term", DbType="NVarChar(50)")]
		public string term
		{
			get
			{
				return this._term;
			}
			set
			{
				if ((this._term != value))
				{
					this.OntermChanging(value);
					this.SendPropertyChanging();
					this._term = value;
					this.SendPropertyChanged("term");
					this.OntermChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RealTimeTable")]
	public partial class RealTimeTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _region;
		
		private string _srcdetail;
		
		private string _areaNm;
		
		private string _UID;
		
		private string _direction;
		
		private string _y1;
		
		private string _happentime;
		
		private string _roadtype;
		
		private string _road;
		
		private string _modDttm;
		
		private string _comment;
		
		private string _happendate;
		
		private string _x1;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void OnsrcdetailChanging(string value);
    partial void OnsrcdetailChanged();
    partial void OnareaNmChanging(string value);
    partial void OnareaNmChanged();
    partial void OnUIDChanging(string value);
    partial void OnUIDChanged();
    partial void OndirectionChanging(string value);
    partial void OndirectionChanged();
    partial void Ony1Changing(string value);
    partial void Ony1Changed();
    partial void OnhappentimeChanging(string value);
    partial void OnhappentimeChanged();
    partial void OnroadtypeChanging(string value);
    partial void OnroadtypeChanged();
    partial void OnroadChanging(string value);
    partial void OnroadChanged();
    partial void OnmodDttmChanging(string value);
    partial void OnmodDttmChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OnhappendateChanging(string value);
    partial void OnhappendateChanged();
    partial void Onx1Changing(string value);
    partial void Onx1Changed();
    #endregion
		
		public RealTimeTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(50)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_srcdetail", DbType="NVarChar(100)")]
		public string srcdetail
		{
			get
			{
				return this._srcdetail;
			}
			set
			{
				if ((this._srcdetail != value))
				{
					this.OnsrcdetailChanging(value);
					this.SendPropertyChanging();
					this._srcdetail = value;
					this.SendPropertyChanged("srcdetail");
					this.OnsrcdetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaNm", DbType="NVarChar(100)")]
		public string areaNm
		{
			get
			{
				return this._areaNm;
			}
			set
			{
				if ((this._areaNm != value))
				{
					this.OnareaNmChanging(value);
					this.SendPropertyChanging();
					this._areaNm = value;
					this.SendPropertyChanged("areaNm");
					this.OnareaNmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UID
		{
			get
			{
				return this._UID;
			}
			set
			{
				if ((this._UID != value))
				{
					this.OnUIDChanging(value);
					this.SendPropertyChanging();
					this._UID = value;
					this.SendPropertyChanged("UID");
					this.OnUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direction", DbType="NVarChar(50)")]
		public string direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				if ((this._direction != value))
				{
					this.OndirectionChanging(value);
					this.SendPropertyChanging();
					this._direction = value;
					this.SendPropertyChanged("direction");
					this.OndirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y1", DbType="NVarChar(50)")]
		public string y1
		{
			get
			{
				return this._y1;
			}
			set
			{
				if ((this._y1 != value))
				{
					this.Ony1Changing(value);
					this.SendPropertyChanging();
					this._y1 = value;
					this.SendPropertyChanged("y1");
					this.Ony1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_happentime", DbType="NVarChar(50)")]
		public string happentime
		{
			get
			{
				return this._happentime;
			}
			set
			{
				if ((this._happentime != value))
				{
					this.OnhappentimeChanging(value);
					this.SendPropertyChanging();
					this._happentime = value;
					this.SendPropertyChanged("happentime");
					this.OnhappentimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roadtype", DbType="NVarChar(50)")]
		public string roadtype
		{
			get
			{
				return this._roadtype;
			}
			set
			{
				if ((this._roadtype != value))
				{
					this.OnroadtypeChanging(value);
					this.SendPropertyChanging();
					this._roadtype = value;
					this.SendPropertyChanged("roadtype");
					this.OnroadtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_road", DbType="NVarChar(50)")]
		public string road
		{
			get
			{
				return this._road;
			}
			set
			{
				if ((this._road != value))
				{
					this.OnroadChanging(value);
					this.SendPropertyChanging();
					this._road = value;
					this.SendPropertyChanged("road");
					this.OnroadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modDttm", DbType="NVarChar(50)")]
		public string modDttm
		{
			get
			{
				return this._modDttm;
			}
			set
			{
				if ((this._modDttm != value))
				{
					this.OnmodDttmChanging(value);
					this.SendPropertyChanging();
					this._modDttm = value;
					this.SendPropertyChanged("modDttm");
					this.OnmodDttmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="NVarChar(600)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_happendate", DbType="NVarChar(50)")]
		public string happendate
		{
			get
			{
				return this._happendate;
			}
			set
			{
				if ((this._happendate != value))
				{
					this.OnhappendateChanging(value);
					this.SendPropertyChanging();
					this._happendate = value;
					this.SendPropertyChanged("happendate");
					this.OnhappendateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_x1", DbType="NVarChar(50)")]
		public string x1
		{
			get
			{
				return this._x1;
			}
			set
			{
				if ((this._x1 != value))
				{
					this.Onx1Changing(value);
					this.SendPropertyChanging();
					this._x1 = value;
					this.SendPropertyChanged("x1");
					this.Onx1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UBikeTable")]
	public partial class UBikeTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int @__id;
		
		private string _sno;
		
		private string _sna;
		
		private string _tot;
		
		private string _sbi;
		
		private string _sarea;
		
		private string _mday;
		
		private string _lat;
		
		private string _lng;
		
		private string _ar;
		
		private string _sareaen;
		
		private string _snaen;
		
		private string _aren;
		
		private string _bemp;
		
		private string _act;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void OnsnoChanging(string value);
    partial void OnsnoChanged();
    partial void OnsnaChanging(string value);
    partial void OnsnaChanged();
    partial void OntotChanging(string value);
    partial void OntotChanged();
    partial void OnsbiChanging(string value);
    partial void OnsbiChanged();
    partial void OnsareaChanging(string value);
    partial void OnsareaChanged();
    partial void OnmdayChanging(string value);
    partial void OnmdayChanged();
    partial void OnlatChanging(string value);
    partial void OnlatChanged();
    partial void OnlngChanging(string value);
    partial void OnlngChanged();
    partial void OnarChanging(string value);
    partial void OnarChanged();
    partial void OnsareaenChanging(string value);
    partial void OnsareaenChanged();
    partial void OnsnaenChanging(string value);
    partial void OnsnaenChanged();
    partial void OnarenChanging(string value);
    partial void OnarenChanged();
    partial void OnbempChanging(string value);
    partial void OnbempChanged();
    partial void OnactChanging(string value);
    partial void OnactChanged();
    #endregion
		
		public UBikeTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int _id
		{
			get
			{
				return this.@__id;
			}
			set
			{
				if ((this.@__id != value))
				{
					this.On_idChanging(value);
					this.SendPropertyChanging();
					this.@__id = value;
					this.SendPropertyChanged("_id");
					this.On_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sno", DbType="NVarChar(50)")]
		public string sno
		{
			get
			{
				return this._sno;
			}
			set
			{
				if ((this._sno != value))
				{
					this.OnsnoChanging(value);
					this.SendPropertyChanging();
					this._sno = value;
					this.SendPropertyChanged("sno");
					this.OnsnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sna", DbType="NVarChar(50)")]
		public string sna
		{
			get
			{
				return this._sna;
			}
			set
			{
				if ((this._sna != value))
				{
					this.OnsnaChanging(value);
					this.SendPropertyChanging();
					this._sna = value;
					this.SendPropertyChanged("sna");
					this.OnsnaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tot", DbType="NVarChar(50)")]
		public string tot
		{
			get
			{
				return this._tot;
			}
			set
			{
				if ((this._tot != value))
				{
					this.OntotChanging(value);
					this.SendPropertyChanging();
					this._tot = value;
					this.SendPropertyChanged("tot");
					this.OntotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sbi", DbType="NVarChar(50)")]
		public string sbi
		{
			get
			{
				return this._sbi;
			}
			set
			{
				if ((this._sbi != value))
				{
					this.OnsbiChanging(value);
					this.SendPropertyChanging();
					this._sbi = value;
					this.SendPropertyChanged("sbi");
					this.OnsbiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sarea", DbType="NVarChar(50)")]
		public string sarea
		{
			get
			{
				return this._sarea;
			}
			set
			{
				if ((this._sarea != value))
				{
					this.OnsareaChanging(value);
					this.SendPropertyChanging();
					this._sarea = value;
					this.SendPropertyChanged("sarea");
					this.OnsareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mday", DbType="NVarChar(50)")]
		public string mday
		{
			get
			{
				return this._mday;
			}
			set
			{
				if ((this._mday != value))
				{
					this.OnmdayChanging(value);
					this.SendPropertyChanging();
					this._mday = value;
					this.SendPropertyChanged("mday");
					this.OnmdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="NVarChar(50)")]
		public string lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				if ((this._lat != value))
				{
					this.OnlatChanging(value);
					this.SendPropertyChanging();
					this._lat = value;
					this.SendPropertyChanged("lat");
					this.OnlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lng", DbType="NVarChar(50)")]
		public string lng
		{
			get
			{
				return this._lng;
			}
			set
			{
				if ((this._lng != value))
				{
					this.OnlngChanging(value);
					this.SendPropertyChanging();
					this._lng = value;
					this.SendPropertyChanged("lng");
					this.OnlngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ar", DbType="NVarChar(100)")]
		public string ar
		{
			get
			{
				return this._ar;
			}
			set
			{
				if ((this._ar != value))
				{
					this.OnarChanging(value);
					this.SendPropertyChanging();
					this._ar = value;
					this.SendPropertyChanged("ar");
					this.OnarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sareaen", DbType="NVarChar(100)")]
		public string sareaen
		{
			get
			{
				return this._sareaen;
			}
			set
			{
				if ((this._sareaen != value))
				{
					this.OnsareaenChanging(value);
					this.SendPropertyChanging();
					this._sareaen = value;
					this.SendPropertyChanged("sareaen");
					this.OnsareaenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snaen", DbType="NVarChar(100)")]
		public string snaen
		{
			get
			{
				return this._snaen;
			}
			set
			{
				if ((this._snaen != value))
				{
					this.OnsnaenChanging(value);
					this.SendPropertyChanging();
					this._snaen = value;
					this.SendPropertyChanged("snaen");
					this.OnsnaenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aren", DbType="NVarChar(100)")]
		public string aren
		{
			get
			{
				return this._aren;
			}
			set
			{
				if ((this._aren != value))
				{
					this.OnarenChanging(value);
					this.SendPropertyChanging();
					this._aren = value;
					this.SendPropertyChanged("aren");
					this.OnarenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bemp", DbType="NVarChar(50)")]
		public string bemp
		{
			get
			{
				return this._bemp;
			}
			set
			{
				if ((this._bemp != value))
				{
					this.OnbempChanging(value);
					this.SendPropertyChanging();
					this._bemp = value;
					this.SendPropertyChanged("bemp");
					this.OnbempChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_act", DbType="NVarChar(50)")]
		public string act
		{
			get
			{
				return this._act;
			}
			set
			{
				if ((this._act != value))
				{
					this.OnactChanging(value);
					this.SendPropertyChanging();
					this._act = value;
					this.SendPropertyChanged("act");
					this.OnactChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
